# Generated by Django 2.2.6 on 2023-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusAccount', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reserve1', models.CharField(max_length=100)),
                ('reserve2', models.CharField(max_length=100)),
                ('reserve3', models.CharField(max_length=100)),
                ('reserve4', models.CharField(max_length=100)),
                ('reserve5', models.CharField(max_length=100)),
                ('cusId', models.CharField(max_length=100)),
                ('booBerth', models.CharField(max_length=100)),
                ('comCode', models.CharField(max_length=100)),
                ('cusTelNumber', models.CharField(max_length=100)),
                ('fliYfare', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BookUser',
                'verbose_name_plural': 'BookUser',
                'db_table': 'book_user',
            },
        ),
    ]
